---
title: 在 'Try' 陳述式中，'Catch' 不可以出現在 'Finally' 之後
ms.date: 07/20/2015
f1_keywords:
- vbc30379
- bc30379
helpviewer_keywords:
- BC30379
ms.assetid: 33d1278b-cf10-4c66-aaf8-08a4372f370b
ms.openlocfilehash: ab300d332dd82870901aec9bd57d8d5d8081a533
ms.sourcegitcommit: f8c270376ed905f6a8896ce0fe25b4f4b38ff498
ms.translationtype: MT
ms.contentlocale: zh-TW
ms.lasthandoff: 06/04/2020
ms.locfileid: "84403767"
---
# <a name="catch-cannot-appear-after-finally-within-a-try-statement"></a>在 'Try' 陳述式中，'Catch' 不可以出現在 'Finally' 之後
`Catch` 陳述式會出現在結尾為 `Finally` 陳述式區塊之 `Try` 後面的程式碼中。 `Catch` 必須出現在 `Try...Catch...Finally` 陳述式區塊內。  
  
 **錯誤 ID︰** BC30379  
  
## <a name="to-correct-this-error"></a>更正這個錯誤  
  
1. 請將 `Catch` 陳述式移至程式碼中的更適當位置。  
  
## <a name="see-also"></a>另請參閱

- [Try...Catch...Finally 陳述式](../language-reference/statements/try-catch-finally-statement.md)
