---
title: 在 'Try' 陳述式中，'Catch' 不可以出現在 'Finally' 之後
ms.date: 07/20/2015
f1_keywords:
- vbc30379
- bc30379
helpviewer_keywords:
- BC30379
ms.assetid: 33d1278b-cf10-4c66-aaf8-08a4372f370b
ms.openlocfilehash: 327bec408905c927c5232297f87b8f54ec941beb
ms.sourcegitcommit: bf5c5850654187705bc94cc40ebfb62fe346ab02
ms.translationtype: MT
ms.contentlocale: zh-TW
ms.lasthandoff: 09/23/2020
ms.locfileid: "91074559"
---
# <a name="catch-cannot-appear-after-finally-within-a-try-statement"></a>在 'Try' 陳述式中，'Catch' 不可以出現在 'Finally' 之後

`Catch` 陳述式會出現在結尾為 `Finally` 陳述式區塊之 `Try` 後面的程式碼中。 `Catch` 必須出現在 `Try...Catch...Finally` 陳述式區塊內。  
  
 **錯誤 ID︰** BC30379  
  
## <a name="to-correct-this-error"></a>更正這個錯誤  
  
1. 請將 `Catch` 陳述式移至程式碼中的更適當位置。  
  
## <a name="see-also"></a>另請參閱

- [Try...Catch...Finally 陳述式](../language-reference/statements/try-catch-finally-statement.md)
